openapi: 3.2.0
info:
  title: Opendock Nova API Documentation Gates API
  description: '## Welcome to Opendock Nova!'
  version: v4.144.0 - 39b4253
  contact: {}
servers:
- url: https://neutron.opendock.com
  description: Production Server
- url: https://neutron.staging.opendock.com
  description: Staging Server
tags:
- name: Gates
paths:
  /gates/{warehouseId}:
    get:
      operationId: GatesController_listGatesByWarehouse
      parameters:
      - name: warehouseId
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatesByWarehouseDto'
      tags:
      - Gates
      security:
      - bearer: []
      summary: Gates controller list gates by warehouse
      x-summary-source: derived
components:
  schemas:
    GatesByWarehouseDto:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
      required:
      - data
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
