openapi: 3.2.0
info:
  title: Opendock Nova API Documentation Audit Log API
  description: '## Welcome to Opendock Nova!'
  version: v4.144.0 - 39b4253
  contact: {}
servers:
- url: https://neutron.opendock.com
  description: Production Server
- url: https://neutron.staging.opendock.com
  description: Staging Server
tags:
- name: Audit Log
paths:
  /audit-log/{objectId}:
    get:
      operationId: AuditLogController_search
      parameters:
      - name: objectId
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuditLog'
      tags:
      - Audit Log
      security:
      - bearer: []
      summary: Audit log controller search
      x-summary-source: derived
components:
  schemas:
    AuditLog:
      type: object
      properties: {}
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
